version: '3.8'

services:
  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  db:
    container_name: db
    image: postgres:13
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data

  node-app:
    container_name: node_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

volumes:
  db_data: {}
  redis_data: {}
